# Generated by Django 5.2.1 on 2025-06-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
